from apps.shared.widgets.select_input import SelectInput
from apps.shared.widgets.radio_select_input import RadioSelectInput
from apps.shared.widgets.date_field_input import DateFieldInput
from apps.shared.widgets.time_field_input import TimeFieldInput
from apps.shared.widgets.date_time_input import DateTimeFieldInput
from apps.shared.widgets.boolean_field_box import BooleanFieldInput
from apps.shared.widgets.char_field_input import CharFieldInput
from apps.shared.widgets.integer_field_input import IntegerFieldInput
from apps.shared.widgets.float_field_input import FloatFieldInput
from apps.shared.widgets.text_field_input import TextFieldInput