services:
  app:
    build: .
    volumes:
      - app-static-files:/var/data/app/static
      - app-media-files:/var/data/app/media
      - app-db-files:/var/data/app/db
    environment:
      DJANGO_DEBUG: 'false'
      DB_NAME: 'postgres'
      DB_USER: 'postgres'
      DB_PASSWORD: 'postgres'
      DB_HOST: 'app-db'
      DJANGO_ALLOWED_HOSTS: '*'
    profiles:
      - all
    restart: always
    [%- if not cookiecutter.nginx -%]
    ports:
      - "8000:80"
    [%- endif %]
    [%- if cookiecutter.postgres -%]
    depends_on:
      - app-db

  app-db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
    restart: always
    profiles:
      - all
      - db
[%- endif %]
[%- if cookiecutter.nginx %]

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/keys/dhparam.pem:/etc/nginx/dhparam.pem:ro
      - ./nginx/keys/server.key:/etc/ssl/private/server.key:ro
      - ./nginx/keys/server.crt:/etc/ssl/certs/server.crt:ro
      - app-static-files:/app/static:ro
      - app-media-files:/app/media:ro
    restart: always
    depends_on:
      - app
    profiles:
      - all
[%- endif %]

volumes:
  app-static-files:
  app-media-files:
  app-db-files:
  [%- if cookiecutter.postgres -%]
  postgres-data:
  [%- endif %]
